-- Drop tables in reverse dependency order (children before parents)
DROP TABLE IF EXISTS HasSkills CASCADE;
DROP TABLE IF EXISTS HasAccounts CASCADE;
DROP TABLE IF EXISTS Accomplices CASCADE;
DROP TABLE IF EXISTS Plans CASCADE;
DROP TABLE IF EXISTS Robberies CASCADE;
DROP TABLE IF EXISTS Skills CASCADE;
DROP TABLE IF EXISTS Robbers CASCADE;
DROP TABLE IF EXISTS Banks CASCADE;
